server:
  port: 8080
  # ssl:
  #   enabled: true
  #   key-store: classpath:cert_and_key.p12
  #   key-store-type: PKCS12
  #   key-store-password: 1234
  servlet:
    context-path: /api
spring:
  profiles:
    active: prod # local : 로컬 , prod : RDS
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
--- # 개발
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/bts;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
--- # 배포
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql.ssafy.io:3306/bts?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: bts
    password: bts!^^20210823
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
--- # AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAW5FCHZWRMVHQNGRB
      secretKey: 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
    s3:
      bucket: bts
    region:
      static: ap-northeast-2 # 서울
    stack:
      auto: false